spring.datasource.url= jdbc:${SPRING_DATASOURCE_URL};MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.sql.init.schema-locations=classpath:/schema-h2.sql
#spring.sql.init.data-locations=classpath:/data-h2.sql
debug=true
logging.level.org.springframework.security=DEBUG

front.endpoint=${BASE_URL_FRONT}
# URL vers la page frontend de r\uFFFDinitialisation
app.reset-password-url=${BASE_URL_FRONT}/schoolchat/reset-password


server.servlet.context-path=/scholchat
server.port=8486

# SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kamsuperold2004@gmail.com
spring.mail.password=adda aneb zeut dqpv
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
app.activation-url=${BASE_URL_FRONT}/schoolchat/account-activation
app.class-approval-url=${BASE_URL_FRONT}/schoolchat/class-approval
app.class-rejection-url=${BASE_URL_FRONT}/schoolchat/class-rejection

# JWT Configuration
jwt.secret=4N4Lg&zNkGzj&B4tmz2X4hTxLVz&LNTD6^L%tFzt2pZ6RkTxL
# 15 minutes
jwt.access-token-expiration=86400000
# 7 jours
jwt.refresh-token-expiration=86400000
# 24 heures
jwt.password-reset-token-expiration=86400000
pending.purge.days=30

# S3 Configuration
#s3.endpoint=http://10.123.111.121:9000

s3.endpoint=https://s3.eu-west-3.amazonaws.com
s3.access-key=${S3_ACCESS_KEY}
s3.secret-key=${S3_SECRET_KEY}
s3.bucket.name=${S3_BUCKET_NAME}
s3.region=eu-west-3
s3.presigned-url.expiry=3600

# Disable AWS SDK region validation (needed for MinIO)
aws.s3.disable-region-detection=true

# Password Encryption Configuration
app.encryption.key=scholchat-secure-key-2024-v1-32b