spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
server.tomcat.connection-timeout=300000

spring.datasource.url=jdbc:postgresql://localhost:5432/scholchat
# to be changed
spring.datasource.username=scholchat_user
spring.datasource.password=StrongPassword123
spring.datasource.driver-class-name=org.postgresql.Driver

debug=true
logging.level.org.springframework.security=DEBUG

front.endpoint=http://localhost:3000
app.reset-password-url=http://localhost:3000/schoolchat/reset-password

server.servlet.context-path=/scholchat
server.port=8486

# SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kamsuperold2004@gmail.com
spring.mail.password=adda aneb zeut dqpv
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
app.activation-url=http://localhost:3000/schoolchat/account-activation
app.class-approval-url=http://localhost:3000/schoolchat/class-approval
app.class-rejection-url=http://localhost:3000/schoolchat/class-rejection
app.renewal-url=http://localhost:3000/schoolchat/renouveler-offre

# JWT Configuration
jwt.secret=4N4Lg&zNkGzj&B4tmz2X4hTxLVz&LNTD6^L%tFzt2pZ6RkTxL
jwt.access-token-expiration=86400000
jwt.refresh-token-expiration=86400000
jwt.password-reset-token-expiration=86400000
jwt.renewal-token-expiration=604800000
pending.purge.days=30

# S3 Configuration (MinIO local)
s3.endpoint=http://localhost:9000
s3.access-key=minioadmin
s3.secret-key=minioadmin
s3.bucket.name=scholchat
s3.bucket.region=us-east-1
s3.presigned-url.expiry=3600

# Password Encryption Configuration
app.encryption.key=scholchat-secure-key-2024-v1-32b

# Jitsi / JaaS Configuration
jitsi.app.id=schoolchat
jitsi.api.key.id=schoolchat
jitsi.domain=api.nguonevents.com
jitsi.secret=scholchat-secure-key-2024-v1-32b
