spring:
  profiles:
    active: local

---
# Profil local : BDD Postgres locale
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/scholchat
    username: scholchat_user
    password: StrongPassword123
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: true

logging:
  level:
    root: DEBUG

---
# Profil prod : BDD Postgres via variables d'environnement / IaC
spring:
  config:
    activate:
      on-profile: prod
  main:
    web-application-type: none
    banner-mode: "off"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    root: DEBUG
